Change folders structure
techmmunity/techmmunity.github.io pull request #118
Opened 2021-05-13 15:28 UTC by Thiago-spart

2021-05-14 00:03 UTC, alessandrohenriqueramos requested changes

2021-05-14 00:03 UTC, alessandrohenriqueramos commented on src/pages/404.tsx
> +import { NotFoundPage } from "web/pages/NotFound";
`NotFoundPage` > `NotFound`

2021-05-14 12:02 UTC, henriqueleite42 commented on .eslintrc.json
> +					"/web/components/",
Esse é `/web/componetes/` mesmo, para que os componentes globais fiquem separados dos componentes especificos daquela pagina.
O `/pages/` Pode ser adicionar em antes (em cima) dele.

2021-05-14 12:03 UTC, henriqueleite42 commented on src/pages/404.tsx
> +import { NotFoundPage } from "web/pages/NotFound";
O correto é `NotFoundPage`, pois é o componente de uma pagina.

2021-05-14 12:03 UTC, henriqueleite42 commented on src/pages/404.tsx
>  import { LayoutsEnum } from "types/enums/layout";
Essa importação está correta.

2021-05-14 12:03 UTC, henriqueleite42 commented on src/pages/404.tsx
>  NotFoundPage.layout = LayoutsEnum.ERROR;
Isso está correto, o layout deve ser passado aqui.

2021-05-14 12:05 UTC, henriqueleite42 commented on src/pages/_app.tsx
> +import { MyApp } from "web/pages/App";
Como o `MyApp` não tem dependencia a algo no NextJs (como o document, que tem uma arquitetura propria), ele deve ser separado e colocado dentro da pasta `src/web/pages`.
Esse comportamento está correto.

2021-05-14 12:05 UTC, henriqueleite42 commented on src/pages/index.tsx
>  import { LayoutsEnum } from "types/enums/layout";
Essa importação está correta.

2021-05-14 12:05 UTC, henriqueleite42 commented on src/pages/index.tsx
> +RedirectToHome.layout = LayoutsEnum.NONE;
Isso está correto, o layout deve ser passado aqui.

2021-05-14 12:06 UTC, henriqueleite42 commented on src/pages/index.tsx
>  		},
Não há necessidade de atribuir uma variavel, já que `defaultLocale` é o padrão usado pela lib de tradução.

2021-05-14 12:07 UTC, henriqueleite42 commented on src/web/pages/App/index.tsx
> +};
Desse modo está correto, pelo que foi respondido previamente nos outros comentátrios.

2021-05-14 12:08 UTC, henriqueleite42 commented on src/web/pages/Home/components/MainSection/index.tsx
> +import { Link } from "web/components/Link";
Essa importação está correta.

2021-05-14 12:08 UTC, henriqueleite42 commented on src/web/pages/Home/index.tsx
> +import { Line } from "web/components/Line";
Essa importação está correta.

2021-05-14 12:09 UTC, henriqueleite42 commented on src/web/pages/NotFound/index.tsx
> +export const NotFoundPage: FCWithLayout = () => (
Desse modo está correto, pelo que foi respondido previamente nos outros comentátrios.

2021-05-14 12:09 UTC, henriqueleite42 commented on src/web/pages/RedirectToHome/index.tsx
> +export const RedirectToHome: FCWithLayout = () => {
Desse modo está correto, pelo que foi respondido previamente nos outros comentátrios

2021-05-14 12:11 UTC, henriqueleite42 commented on src/web/pages/RedirectToHome/index.tsx
> +				push(`/${i18n.defaultLocale}`);
O correto seria separar o `case language.startsWith("en-"):` do `default:`, desse modo:
```ts
case language.startsWith("en-"):
  push("/en-US");
default:
  push(`/${i18n.defaultLocale}`);
```

2021-05-14 12:12 UTC, henriqueleite42 commented on src/web/pages/RedirectToHome/index.tsx
> +import { i18n } from "../../../../next-i18next.config";
Essa importação será usada, isso está correto.

2021-05-14 12:18 UTC, henriqueleite42 requested changes

2021-05-14 12:18 UTC, henriqueleite42 commented on src/web/pages/Home/index.tsx
> +export const Home: FCWithLayout = () => (
Alterar nome para `HomePage`

2021-05-14 12:18 UTC, henriqueleite42 commented on src/web/pages/RedirectToHome/index.tsx
> +export const RedirectToHome: FCWithLayout = () => {
Alterar nome para `RedirectToHomePage`

2021-05-15 18:46 UTC, alessandrohenriqueramos commented on src/pages/index.tsx
>  		},
e a forma que é usada nas outras páginas

2021-05-15 18:53 UTC, alessandrohenriqueramos requested changes

2021-05-15 18:53 UTC, alessandrohenriqueramos commented on .eslintrc.json
> +					"/web/components/",
`/pages/` em cima da linha 68

2021-05-16 21:29 UTC, henriqueleite42 commented on src/pages/index.tsx
>  		},
Deve ser trocado nas outras paginas para usar o `i18n.defaultLocale`

2021-05-16 23:39 UTC, henriqueleite42 approved these changes

2021-05-16 23:40 UTC, alessandrohenriqueramos approved these changes

2021-05-16 23:40 UTC, merged