Add footer
techmmunity/techmmunity.github.io pull request #12
Opened 2021-04-12 13:40 UTC by alessandrohenriqueramos

2021-04-12 13:41 UTC, alessandrohenriqueramos commented on src/styles/GlobalStyle.ts
> +      font-size: 52.5%;
Alterado porque estava muito pequeno no mobile

2021-04-12 22:22 UTC, henriqueleite42 requested changes

2021-04-12 22:22 UTC, henriqueleite42 commented on src/components/Footer/index.tsx
> +						&copy; {year} Techmmunity. All rights reserved.
Alterar para `© 2020 Techhmunity All Rights Reserved`

2021-04-12 22:22 UTC, henriqueleite42 commented on src/components/Footer/index.tsx
> +						<a target="_blank">
https://www.twitch.tv/techmmunity

2021-04-12 22:22 UTC, henriqueleite42 commented on src/components/Footer/index.tsx
> +						<a target="_blank">
https://www.youtube.com/channel/UCl322bbCTdwW-eOEO4J0Zxw

2021-04-12 22:22 UTC, henriqueleite42 commented on src/components/Footer/index.tsx
> +						<a target="_blank">
https://www.facebook.com/techmmunity/

2021-04-12 22:22 UTC, henriqueleite42 commented on src/components/Footer/index.tsx
> +						<a target="_blank">
https://twitter.com/techmmunity1

2021-04-12 22:22 UTC, henriqueleite42 commented on src/components/Footer/index.tsx
> +						<a target="_blank">
https://www.linkedin.com/company/71251333/

2021-04-12 22:22 UTC, henriqueleite42 commented on src/components/Footer/index.tsx
> +						<a target="_blank">
Adicionar `rel="noopener noreferrer"`, a não ser que o Next já adicione sozinho
(Isso é valido para TODOS os outros <a> do projeto)

2021-04-12 22:22 UTC, henriqueleite42 commented on src/components/Footer/index.tsx
> +						<a target="_blank">
Adicionar `rel="noopener noreferrer"`, a não ser que o Next já adicione sozinho
(Isso é valido para TODOS os outros <a> do projeto)

2021-04-12 22:22 UTC, henriqueleite42 commented on src/components/Footer/index.tsx
> +						<a target="_blank">
Adicionar `rel="noopener noreferrer"`, a não ser que o Next já adicione sozinho
(Isso é valido para TODOS os outros <a> do projeto)

2021-04-12 22:22 UTC, henriqueleite42 commented on src/components/Footer/index.tsx
> +						<a target="_blank">
Adicionar `rel="noopener noreferrer"`, a não ser que o Next já adicione sozinho
(Isso é valido para TODOS os outros <a> do projeto)

2021-04-12 22:22 UTC, henriqueleite42 commented on src/components/Footer/styles.ts
> +	${IconCSS}
Não daria pra estilizar o proprio link do next ao invez de estilizar 1 por 1?

2021-04-12 22:22 UTC, henriqueleite42 commented on src/pages/_app.tsx
> +		<Footer />
O footer é fixo lá no final da pagina, né? Não tem um corpotamento de sticky?

2021-04-13 13:58 UTC, henriqueleite42 requested changes

2021-04-13 17:35 UTC, henriqueleite42 approved these changes

2021-04-13 17:35 UTC, merged