Add 404 page title
techmmunity/techmmunity.github.io pull request #136
Opened 2021-05-31 18:04 UTC by Thiago-spart

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] I followed GitFlow pattern to create the branch
- [ ] My code produces no warnings or errors in the console
- [x] Tests for the changes have been added / updated
- [ ] Docs have been added / updated

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?
The old title wasn't good
## What is the new behavior?
The new is more beautiful and  brings the techmmunity name
## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information (Prints, details, etc)

2021-05-31 21:01 UTC, henriqueleite42 requested changes

2021-05-31 21:01 UTC, henriqueleite42 commented on src/web/components/HeadTitle/index.tsx
> +export const HeadTitle: React.FC<Props> = ({title}) => (
`({title})` -> `({ title })`
Ps: Ativa o ESLint q ele corrige essas coisas sozinho

2021-05-31 21:01 UTC, henriqueleite42 commented on src/web/pages/NotFound/index.tsx
> +		<HeadTitle title={"Not found"} />
`title={"Not found"}` -> `title="Not found"`

2021-05-31 21:08 UTC, henriqueleite42 approved these changes

2021-06-01 00:02 UTC, alessandrohenriqueramos approved these changes

2021-06-01 15:46 UTC, merged