Main head title
techmmunity/techmmunity.github.io pull request #137
Opened 2021-06-01 19:22 UTC by Thiago-spart

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] I followed GitFlow pattern to create the branch
- [x] My code produces no warnings or errors in the console
- [x] Tests for the changes have been added / updated
- [x] Docs have been added / updated

## PR Type

What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?
The old head wasn't using the HeadTitle component
## What is the new behavior?
The new has a better behavior and uses HeadTitle 
## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information (Prints, details, etc)

2021-06-01 19:27 UTC, henriqueleite42 approved these changes

2021-06-01 22:00 UTC, henriqueleite42 submitted a review, later dismissed

2021-06-02 00:45 UTC, aleessandrohr requested changes

2021-06-02 10:28 UTC, alessandrohenriqueramos requested changes

2021-06-02 10:28 UTC, alessandrohenriqueramos commented on src/assets/translations/en-US/home.json
> +		},
Acima da `mainSection`

2021-06-02 10:28 UTC, alessandrohenriqueramos commented on src/assets/translations/pt-BR/home.json
> +		},
Acima da `mainSection`

2021-06-02 10:28 UTC, alessandrohenriqueramos commented on src/web/pages/Home/index.tsx
> +			<HeadTitle title={t("mainSection.head.title")} />
Atualizar a string

2021-06-02 18:27 UTC, henriqueleite42 requested changes

2021-06-02 18:27 UTC, henriqueleite42 commented on src/assets/colors.ts
> +import { COLORS as CoreColors } from "core/assets/colors";
`CoreColors` -> `CORE_COLORS`

2021-06-02 18:31 UTC, henriqueleite42 submitted a review, later dismissed

2021-06-02 21:13 UTC, alessandrohenriqueramos approved these changes

2021-06-02 22:36 UTC, henriqueleite42 approved these changes

2021-06-02 22:46 UTC, merged