Lateral padding of PageContainer
techmmunity/techmmunity.github.io pull request #138
Opened 2021-06-01 21:34 UTC by Thiago-spart

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] I followed GitFlow pattern to create the branch
- [x] My code produces no warnings or errors in the console
- [x] Tests for the changes have been added / updated
- [x] Docs have been added / updated

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?
The old media querie was not necessary
## What is the new behavior?
Now instead of querie we have a padding in the links
## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information (Prints, details, etc)

2021-06-01 22:00 UTC, henriqueleite42 approved these changes, later dismissed

2021-06-02 00:13 UTC, alessandrohenriqueramos commented on src/web/pages/Home/components/MainSection/styles.ts
> +	padding: 0 2rem;
É pra alterar no `PageContainer`, defazer todas essas alterações

2021-06-02 00:14 UTC, alessandrohenriqueramos requested changes

2021-06-02 00:14 UTC, alessandrohenriqueramos commented on src/web/pages/Home/components/MainSection/styles.ts
> +	padding: 0 2rem;
É pra alterar no `PageContainer`, desfazer todas essas alterações

2021-06-02 10:31 UTC, alessandrohenriqueramos requested changes

2021-06-02 10:31 UTC, alessandrohenriqueramos commented on src/web/pages/Home/components/MainSection/styles.ts
> +			padding-top: 2rem;
desfazer alteração

2021-06-02 18:29 UTC, henriqueleite42 requested changes

2021-06-02 18:29 UTC, henriqueleite42 commented on src/assets/colors.ts
> +import { COLORS as CoreColors } from "core/assets/colors";
`CoreColors` -> `CORE_COLORS`

2021-06-02 18:31 UTC, henriqueleite42 approved these changes, later dismissed

2021-06-02 21:09 UTC, alessandrohenriqueramos approved these changes

2021-06-02 21:10 UTC, merged