Add techmmunity config
techmmunity/techmmunity.github.io pull request #141
Opened 2021-06-02 20:58 UTC by alessandrohenriqueramos

## What this PR introduces?

Add Techmmunity Style Guide

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] I followed GitFlow pattern to create the branch
- [x] My code produces no warnings or errors in the console
- [x] Tests for the changes have been added / updated
- [x] The changes made are accessible
- [x] The changes made are responsive

## PR Type

What kind of change does this PR introduce?

```
[ ] Hotfix
[ ] Bugfix
[ ] Feature
[ ] Documentation update
[x] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] CI/CD related changes
```

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information (Prints, details, etc)

2021-06-02 23:46 UTC, henriqueleite42 requested changes

2021-06-02 23:46 UTC, henriqueleite42 commented on package.json
>  		"eslint-config-prettier": "^8.1.0",
Essa config aqui eu tenho quase certeza que pode ser removida, remover e testar, por favor.

2021-06-02 23:46 UTC, henriqueleite42 commented on src/pages/[language]/index.tsx
> +	const language = (params?.language ?? i18n.defaultLocale) as string;
Reverter alteração

2021-06-02 23:46 UTC, henriqueleite42 commented on src/types/window.d.ts
>  // eslint-disable-next-line prettier/prettier
Remover essa linha (Se o eslint reclamar é por cause de algum formatador que está dando conflito com o eslint)

2021-06-02 23:46 UTC, henriqueleite42 commented on src/utils/gtm.ts
> +export const gtmPageView = (url: string) => {
Alterar nome para `setGtmPageView`

2021-06-03 22:39 UTC, alessandrohenriqueramos commented on package.json
>  		"eslint-config-prettier": "^8.1.0",
precisa do pacote

2021-06-04 11:33 UTC, henriqueleite42 approved these changes

2021-06-04 11:34 UTC, merged