Convert cards into array
techmmunity/techmmunity.github.io pull request #61
Opened 2021-04-23 23:59 UTC by alessandrohenriqueramos

2021-04-24 00:12 UTC, henriqueleite42 requested changes

2021-04-24 00:12 UTC, henriqueleite42 commented on src/assets/languages/en-US.ts
> +import { AiFillLike } from "react-icons/ai";
Remover icones desse arquivo. Aqui devem conter apenas textos.

2021-04-24 00:12 UTC, henriqueleite42 commented on src/assets/languages/en-US.ts
> +			id: MadeForEveryoneCardEnum.GRAPHIC,
Remover dados que não forem textos desse arquivo.

2021-04-24 12:32 UTC, henriqueleite42 requested changes

2021-04-24 12:32 UTC, henriqueleite42 commented on src/assets/languages/en-US.ts
>  				"Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe, qui. Omnis illum assumenda voluptates corrupti fuga iste? Totam repellat exercitationem sint sit iusto laboriosam, asperiores ad t
Aproveitar para já adicionar os textos corretos

2021-04-24 12:32 UTC, henriqueleite42 commented on src/components/FeedbackSection/index.tsx
> +		url: EN.feedbackTexts.third.url,
O url tbm deve ser hardcoded aqui

2021-04-24 12:32 UTC, henriqueleite42 commented on src/components/FeedbackSection/index.tsx
> +		author: "People 3",
Já aproveitar para adicionar os nomes corretos

2021-04-24 12:32 UTC, henriqueleite42 commented on src/components/MadeForEveryoneSection/components/Cards/index.tsx
> +		url: EN.madeForEveryoneTexts.dev.url,
O url deve ser hardcoded aqui

2021-04-24 12:32 UTC, henriqueleite42 commented on src/components/MadeForEveryoneSection/components/Cards/index.tsx
> +		alt: EN.madeForEveryoneTexts.dev.alt,
O valor `EN.madeForEveryoneTexts.dev.title` pode ser usado como alt

2021-04-24 12:32 UTC, henriqueleite42 commented on src/components/MadeForEveryoneSection/components/Cards/index.tsx
> +		{madeForEveryoneCards.map(({ id, ...rest }) => (
Alterar `rest` para `props`

2021-04-24 12:32 UTC, henriqueleite42 commented on src/types/enums/MadeForEveryoneCardEnum.ts
> +export enum MadeForEveryoneCardEnum {
Se não estiver sendo usado, remover

2021-04-24 19:39 UTC, alessandrohenriqueramos commented on src/types/enums/MadeForEveryoneCardEnum.ts
> +export enum MadeForEveryoneCardEnum {
Ela é usada

2021-04-24 20:24 UTC, henriqueleite42 requested changes

2021-04-24 20:24 UTC, henriqueleite42 commented on src/assets/languages/en-US.ts
> +	feedbackTexts: {
`feedbackTexts` > `feedbackSection`

2021-04-24 20:24 UTC, henriqueleite42 commented on src/assets/languages/en-US.ts
> +	madeForEveryoneTexts: {
madeForEveryoneSection

2021-04-24 20:24 UTC, henriqueleite42 commented on src/assets/languages/en-US.ts
> +	madeOfTexts: {
madeOfSection

2021-04-24 20:24 UTC, henriqueleite42 commented on src/assets/languages/en-US.ts
> +			first: {
`first` > `alessandroRamos`

2021-04-24 20:24 UTC, henriqueleite42 commented on src/assets/languages/en-US.ts
> +			second: {
`second` > `diegoPinheiro`

2021-04-24 20:24 UTC, henriqueleite42 commented on src/assets/languages/en-US.ts
> +			third: {
`third` > `plactronic`

2021-04-24 20:24 UTC, henriqueleite42 commented on src/assets/languages/en-US.ts
>  	cookiesMessage: {
cookiesAlertModal

2021-04-24 20:24 UTC, henriqueleite42 commented on src/components/MadeForEveryoneSection/components/Cards/index.tsx
> +		id: MadeForEveryoneCardEnum.DEV,
Como são ids, caso o enum seja usado apenas aqui, pode colocar direto o valor dele.

2021-04-24 20:24 UTC, henriqueleite42 commented on src/components/MadeForEveryoneSection/components/Cards/index.tsx
> +		invertOrder: MadeForEveryoneCardEnum.DEV % 2 === 0,
InvertOrder é uma prop que pode ser definida dinamicamente baseado na prop id

2021-04-24 20:24 UTC, henriqueleite42 commented on src/types/enums/MadeForEveryoneCardEnum.ts
> +export enum MadeForEveryoneCardEnum {
Remover

2021-04-25 02:36 UTC, henriqueleite42 approved these changes

2021-04-25 02:37 UTC, merged