add pt-br translation
techmmunity/techmmunity.github.io pull request #83
Opened 2021-04-30 20:11 UTC by Thiago-spart

2021-04-30 20:25 UTC, alessandrohenriqueramos requested changes

2021-04-30 20:25 UTC, alessandrohenriqueramos commented on public/locales/pt-BR/common.json
> +	},
remover esse `mainContainer` da linha 8 e deixar apenas `title` da linha 9

2021-04-30 20:25 UTC, alessandrohenriqueramos commented on public/locales/pt-BR/common.json
> +		}
trocar `mainContainer` para `description` na linha 13, remover `aboutUsLinkText` e `communityLinkText` desse objeto e colocar em um objeto chamado `links` e ele deve ficar abaixo do objeto `description`

2021-04-30 20:25 UTC, alessandrohenriqueramos commented on public/locales/pt-BR/common.json
> +		},
substituir `mainContainer` por `description` na linha 21

2021-04-30 20:25 UTC, alessandrohenriqueramos commented on public/locales/pt-BR/common.json
> +		},
substituir`madeDescription` e deixar apenas `description`

2021-04-30 20:25 UTC, alessandrohenriqueramos commented on public/locales/pt-BR/common.json
> +				"button": "Saiba mais"
remover esse `button` da linha 46, não existe nenhum button de "Saiba mais" na section

2021-04-30 20:25 UTC, alessandrohenriqueramos commented on public/locales/pt-BR/common.json
> +	},
remover esse `mainContainer` e substituir `copywriteText` por `copyright`

2021-04-30 20:52 UTC, henriqueleite42 requested changes

2021-04-30 20:52 UTC, henriqueleite42 commented on public/locales/pt-BR/common.json
> +				"button": "Saiba mais"
Houve uma confusão aqui, o botão fica na section de `TechmmunityDivisions`

2021-04-30 20:52 UTC, henriqueleite42 commented on public/locales/pt-BR/common.json
>  		}
Adicionar aqui o botão de "Saiba Mais" `buttons: { learnMore: "adasd" }`

2021-04-30 20:58 UTC, henriqueleite42 commented on public/locales/pt-BR/common.json
>  		}
Faz sentido, a tag é um `<a>`, né?

2021-04-30 20:59 UTC, alessandrohenriqueramos commented on public/locales/pt-BR/common.json
>  		}
sim, a tag é um `<a>`

2021-04-30 21:11 UTC, alessandrohenriqueramos requested changes

2021-04-30 21:11 UTC, alessandrohenriqueramos commented on public/locales/pt-BR/common.json
>  			},
o "Saiba mais" deve ficar dentro de um objeto `learnMore` e dentro desse `links`, isso é válido pra todos os "Saiba mais"

2021-04-30 21:16 UTC, henriqueleite42 requested changes

2021-04-30 21:16 UTC, henriqueleite42 commented on public/locales/pt-BR/common.json
> +				"links": "Saiba mais"
Remover links daqui, ele deve ser uma unica prop, que fique no mesmo nivel de cards e inputs

2021-04-30 21:16 UTC, henriqueleite42 commented on public/locales/pt-BR/common.json
> +				"textLabel": "Programação"
Remover `textLabel` de todos os inputs e deixar apenas o texto. Ex: `dev: "text"`

2021-04-30 21:16 UTC, henriqueleite42 commented on public/locales/pt-BR/common.json
> +				"feedback": "A comunidade é muito acolhedora, eu sempre tive medo de fazer perguntas em outras comunidades, porque achava que elas eram \"perguntas estúpidas demais\", mas na Techmmunity, as pess
Remover prop feedback e deixar apenas o nome da pessoa. Ex: `nome: "text"`

2021-04-30 21:16 UTC, henriqueleite42 commented on public/locales/pt-BR/common.json
> +			"aboutUsLinkText": "Saiba mais sobre nós",
Remover `Link` do nome dessas 2 props

2021-05-01 00:06 UTC, alessandrohenriqueramos approved these changes

2021-05-01 00:08 UTC, henriqueleite42 approved these changes

2021-05-01 00:08 UTC, merged