Update vccode settings
techmmunity/techmmunity.github.io pull request #86
Opened 2021-05-01 20:59 UTC by Thiago-spart

2021-05-02 00:12 UTC, henriqueleite42 requested changes

2021-05-02 00:12 UTC, henriqueleite42 commented on .vscode/settings.json
> +
Remover essa linha

2021-05-02 00:12 UTC, henriqueleite42 commented on .vscode/settings.json
> +
Remover essa linha

2021-05-02 00:12 UTC, henriqueleite42 commented on .vscode/settings.json
> +
Remover essa linha

2021-05-02 00:12 UTC, henriqueleite42 commented on .vscode/settings.json
> +
Remover essa linha

2021-05-02 00:12 UTC, henriqueleite42 commented on .vscode/settings.json
> +
Remover essa linha

2021-05-02 00:12 UTC, henriqueleite42 commented on .vscode/settings.json
> +
Remover essa linha

2021-05-02 00:12 UTC, henriqueleite42 commented on .vscode/settings.json
> +
Remover essa linha

2021-05-02 00:12 UTC, henriqueleite42 commented on .vscode/settings.json
> +
Remover essa linha

2021-05-02 00:12 UTC, henriqueleite42 commented on .vscode/settings.json
> +
Remover essa linha

2021-05-02 00:12 UTC, henriqueleite42 commented on .vscode/settings.json
> +
Remover essa linha

2021-05-02 00:12 UTC, henriqueleite42 commented on .vscode/settings.json
> +
Remover essa linha

2021-05-02 00:12 UTC, henriqueleite42 commented on .vscode/settings.json
> +
Remover essa linha

2021-05-02 00:12 UTC, henriqueleite42 commented on .vscode/settings.json
> +
Remover essa linha

2021-05-02 00:12 UTC, henriqueleite42 commented on .vscode/settings.json
> +
Remover essa linha

2021-05-02 16:52 UTC, alessandrohenriqueramos requested changes

2021-05-02 16:52 UTC, alessandrohenriqueramos commented on src/components/Footer/styles.ts
>  `;
reverter alteração

2021-05-02 16:52 UTC, alessandrohenriqueramos commented on src/components/Footer/styles.ts
> +	}
reverter alteração

2021-05-02 23:21 UTC, alessandrohenriqueramos approved these changes

2021-05-03 00:01 UTC, henriqueleite42 approved these changes

2021-05-03 00:01 UTC, merged