Create change language button
techmmunity/techmmunity.github.io pull request #99
Opened 2021-05-07 04:05 UTC by Thiago-spart

2021-05-07 11:05 UTC, henriqueleite42 requested changes

2021-05-07 11:05 UTC, henriqueleite42 commented on src/components/MainSection/components/RedirectButtons/index.tsx
> +			<ChangeButton id="1" active={query.language === "en-US"}>
ID é uma prop para identificar um elemento no contexto global do site, jamais deve ser usado para regras de negocio desse tipo. Existem outros jeitos de se fazer isso, refletir sobre o problema e mudar isso.

2021-05-07 11:05 UTC, henriqueleite42 commented on src/components/MainSection/components/RedirectButtons/styles.ts
> +		Number(id) == 1 ? "5px 0 0 5px" : "0 5px 5px 0"};
Adicionar um espaço entre essa linha e as `pseudo-classes`.

2021-05-07 11:06 UTC, henriqueleite42 requested changes

2021-05-07 11:06 UTC, henriqueleite42 commented on src/components/MainSection/components/RedirectButtons/styles.ts
> +export const ChangeButton = styled.div<{ (active: boolean, id: string) }>`
`<{ active: boolean, id: string }>`

2021-05-07 11:22 UTC, alessandrohenriqueramos commented on src/components/MainSection/components/RedirectButtons/styles.ts
> +export const ChangeButton = styled.div<{ (active: boolean, id: string) }>`
é `<{ active: boolean; id: string }>`

2021-05-08 11:59 UTC, henriqueleite42 requested changes

2021-05-08 11:59 UTC, henriqueleite42 commented on src/components/MainSection/components/RedirectButtons/index.tsx
> +			<ChangeButton value="1" active={query.language === "en-US"}>
Desse modo não está intuitivo, pensar mais um pouco sobre como resolver o problema.

2021-05-08 19:51 UTC, alessandrohenriqueramos requested changes

2021-05-09 21:28 UTC, henriqueleite42 approved these changes, later dismissed

2021-05-10 11:20 UTC, alessandrohenriqueramos requested changes

2021-05-10 11:20 UTC, alessandrohenriqueramos commented on src/components/MainSection/components/RedirectButtons/index.tsx
> +	const { query } = useRouter();
alterar o nome do componente e do arquivo para `RedirectLinks`

2021-05-10 11:20 UTC, alessandrohenriqueramos commented on src/components/MainSection/components/RedirectButtons/index.tsx
> +			</RedirectButton>
`RedirectButton` > `RedirectLink`

2021-05-12 18:28 UTC, alessandrohenriqueramos approved these changes

2021-05-12 19:00 UTC, henriqueleite42 approved these changes

2021-05-12 19:00 UTC, merged